src/Entity/beer.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BeerRepository")
 */
class beer
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
    * @ORM\Column(type="string", length=100)
    * @Assert\NotBlank(
    * message="Title can't be empty !"
    * )
    */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $published_at;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=2)
     * @Assert\NotNull(
     * message="Price can't be null !"
     * )
     */
    private $Price;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Country", inversedBy="beersNew", cascade={"persist"})
     */
    private $country_id;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\categorie", inversedBy="beers")
     */
    private $categorie;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Client", inversedBy="beer")
     */
    private $client;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Client", inversedBy="beer")
     */
    private $beer;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Client", inversedBy="beer")
     */
    private $clientNew;

    /**
     * @ORM\Column(type="decimal", precision=3, scale=1, nullable=true)
     */
    private $degree;

    const NOTE_GOOD = 'good';
    const NOTE_VERY_GOOD = 'very good';
    const NOTE_BAD = 'bad';
    const NOTE_NOT_GOOD = 'not good';

    /**
    * @ORM\Column(type="string", length=100, nullable=true)
    */
    private $note;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BeerUser", mappedBy="beer_id")
     */
    private $beerUsers;

    public function __construct()
    {
        $this->categorie = new ArrayCollection();
        $this->clients = new ArrayCollection();
        $this->beerUsers = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->published_at;
    }

    public function setPublishedAt(?\DateTimeInterface $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }
    

    public function getPrice()
    {
        return $this->Price;
    }

    public function setPrice($Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getCountryId(): ?Country
    {
        return $this->country_id;
    }

    public function setCountryId(?Country $country_id): self
    {
        $this->country_id = $country_id;

        return $this;
    }

    /**
     * @return Collection|categorie[]
     */
    public function getCategorie(): Collection
    {
        return $this->categorie;
    }

    public function addCategorie(Categorie $categorie): self
    {
        if (!$this->categorie->contains($categorie)) {
            $this->categorie[] = $categorie;
            // associer les bières au catégorie
            $categorie->addBeer($this);
        }

        return $this;
    }

    public function removeCategorie(Categorie $categorie): self
    {
        if ($this->categorie->contains($categorie)) {
            $this->categorie->removeElement($categorie);
        }

        return $this;
    }

    public function getClientNew(): ?Client
    {
        return $this->clientNew;
    }

    public function setClientNew(?Client $clientNew): self
    {
        $this->clientNew = $clientNew;

        return $this;
    }

    public function getDegree()
    {
        return $this->degree;
    }

    public function setDegree($degree): self
    {
        $this->degree = $degree;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): self
    {
        if (!in_array($note, [
            self::NOTE_BAD, self::NOTE_GOOD,
            self::NOTE_NOT_GOOD,
            self::NOTE_VERY_GOOD])){
            throw new \InvalidArgumentException("Invalid note");
    }
        $this->note = $note;
        return $this;
    }

    /**
     * @return Collection|BeerUser[]
     */
    public function getBeerUsers(): Collection
    {
        return $this->beerUsers;
    }

    public function addBeerUser(BeerUser $beerUser): self
    {
        if (!$this->beerUsers->contains($beerUser)) {
            $this->beerUsers[] = $beerUser;
            $beerUser->setBeerId($this);
        }

        return $this;
    }

    public function removeBeerUser(BeerUser $beerUser): self
    {
        if ($this->beerUsers->contains($beerUser)) {
            $this->beerUsers->removeElement($beerUser);
            // set the owning side to null (unless already changed)
            if ($beerUser->getBeerId() === $this) {
                $beerUser->setBeerId(null);
            }
        }

        return $this;
    }

}

src/Controller/BarController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\DataFixtures\{AppFixtures,AppFixturesCountry,AppFixturesCategorie,AppFixturesClient,UserFixtures,BeerUserFixtures};
use Symfony\Component\HttpFoundation\Response;
use App\Entity\{beer,Country,categorie,Client,User,BeerUser};
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Faker;


class BarController extends AbstractController
{

    /**
     * @Route("/bar", name="bar")
     */
    public function index()
    {
        $repository = $this->getDoctrine()->getRepository(Beer::class);
        $beers = $repository->findAll();
        $repository = $this->getDoctrine()->getRepository(Country::class);
        $countries = $repository->findAll();

        return $this->render('bar/index.html.twig', [
            'controller_name' => 'BarController',
            'title' => 'La page index des bières',
            'beers' => $beers,
            'countries' => $countries,
        ]);
    }

    /**
    * @Route("/beers/{slug}", name="show_beer")
    */

    public function show(string $slug){
        
        $repository = $this->getDoctrine()->getRepository(beer::class);
        $beers = $repository->findAll();

        return $this->render('bar/beer.html.twig', [
            'title' => 'Beers',
            'beers' => $beers[$slug],
        ]);
        }

    /**
    * @Route("/country/{slug}", name="show_country")
    */

    public function showCountry(string $slug){
        
        $repository = $this->getDoctrine()->getRepository(Country::class);
        $countries = $repository->findAll();

        return $this->render('bar/country.html.twig', [
            'title' => $countries[$slug]->getName(),
            'country' => $countries[$slug],
        ]);
        }


    /**
    * @Route("/newbeer", name="create_beer")
    */
    public function createBeer(ObjectManager $manager){
        
        $entityManager = $this->getDoctrine()->getManager();
        $repository = $this->getDoctrine()->getRepository(beer::class);
        $beers = $repository->findAll();
        $faker = Faker\Factory::create('fr_FR');

        foreach($beers as $beer){
            $beer->setDegree($faker->randomFloat($nbMaxDecimals = 1, $min = 1, $max = 37));
            $r=rand(0,3);
            $note = ['very good','good','not good','bad'];
            $beer->setNote($note[$r]);
            $manager->persist($beer);
            $manager->flush();
        }

        return new Response('Saved new beer with id '.$faker->randomFloat($nbMaxDecimals = 1, $min = 1, $max = 37));
        
        }
    


    /**
    * @Route("/newcountry", name="create_country")
    */
    public function createCountry(){

        $entityManager = $this->getDoctrine()->getManager();

        $AppFixturesCountry = new AppFixturesCountry;

        $country = $AppFixturesCountry->load($entityManager);

        return new Response('Saved new country with id '.$country->getId());
        
        }

    /**
    * @Route("/newcategorie", name="create_categorie")
    */
    public function createCategorie(){

        $entityManager = $this->getDoctrine()->getManager();

        $AppFixturesCategorie = new AppFixturesCategorie;

        $categorie = $AppFixturesCategorie->load($entityManager);

        return new Response('Saved new country with id '.$categorie->getId());
        
        }

    /**
    * @Route("/newclient", name="create_client")
    */
    public function createClient(){

        $entityManager = $this->getDoctrine()->getManager();

        $AppFixturesClient = new AppFixturesClient;

        $client = $AppFixturesClient->load($entityManager);

        return new Response('Saved new Client with id '.$client->getId());
        
        }

    /**
    * @Route("/newuser", name="create_user")
    */
    public function createUser(){

        $entityManager = $this->getDoctrine()->getManager();

        $UserFixtures = new UserFixtures;

        $user = $UserFixtures->load($entityManager);

        return new Response('Saved new Client with id '.$user->getId());
        
        }
    
    /**
    * @Route("/newbeeruser", name="create_beeruser")
    */
    public function createBeerUser(){

        $entityManager = $this->getDoctrine()->getManager();

        $BeerUserFixtures = new BeerUserFixtures;

        $beeruser = $BeerUserFixtures->load($entityManager);

        return new Response('Saved new Client with id '.$beeruser->getId());
        
        }

    /**
    * @Route("/beeruserfill", name="beer_user_fill")
    */
    public function beerUserFill(ObjectManager $manager){
        $repository = $this->getDoctrine()->getRepository(beer::class);
        $beers = $repository->findAll();

        $repository = $this->getDoctrine()->getRepository(User::class);
        $users = $repository->findAll();

        foreach($users as $user){
            $r=rand(1,30);
            $beeruser = new BeerUser();

            $beeruser->setBeerId($beers[$r]);
            $beeruser->setDegree($beers[$r]->getDegree());
            $beeruser->setNote($beers[$r]->getNote());
            $beeruser->setUserId($user);
            
            $manager->persist($beeruser);
            $manager->flush();
        }
        return new Response('BeerUser filled !');
    }
    /**
    * @Route("/clientfill", name="client_fill")
    */
    public function clientfill(ObjectManager $manager){

        $repository = $this->getDoctrine()->getRepository(beer::class);
        $beers = $repository->findAll();
        
        $repository = $this->getDoctrine()->getRepository(Client::class);
        $clients = $repository->findAll();

        foreach($clients as &$client){
            $r1 = rand(0,29);
            $r2 = rand(0,29);
            $r3 = rand(0,29);

            $client->addBeer($beers[$r1]);
            $client->addBeer($beers[$r2]);
            $client->addBeer($beers[$r3]);          
            
            $categories1 = $beers[$r1]->getCategorie();
            $categories2 = $beers[$r2]->getCategorie();
            $categories3 = $beers[$r3]->getCategorie(); 

            $client->addCategorie($categories1[0]);
            $client->addCategorie($categories2[0]);
            $client->addCategorie($categories3[0]);
        }

            $manager->persist($client);
            $manager->flush();
            return new Response('Saved new beer on country with id');
    }



    /**
    * @Route("/countryadder", name="country_adder")
    */
    public function countryAdder(ObjectManager $manager){

        $repository = $this->getDoctrine()->getRepository(beer::class);
        $beers = $repository->findAll();

        foreach($beers as &$beer){

            $repository = $this->getDoctrine()->getRepository(Country::class);
            $countries = $repository->findAll();

            $r=rand(0,3);
            $beer->setCountryId($countries[$r]);

            $manager->persist($beer);
            $manager->flush();

        }
        return new Response('Saved new beer with id '.$r);
    }

    /**
    * @Route("/beeradder", name="beer_adder")
    */
    public function beerAdder(ObjectManager $manager){

        $repository = $this->getDoctrine()->getRepository(beer::class);
        $beers = $repository->findAll();
        
        $repository = $this->getDoctrine()->getRepository(Country::class);
        $countries = $repository->findAll();

        foreach($countries as &$country){

            foreach($beers as $beer){
                if($country == $beer->getCountryId()){
                    $country->addBeersNew($beer);
                }
            }
        }

            $manager->persist($beer);
            $manager->flush();
            return new Response('Saved new beer on country with id');
    }


    /**
    * @Route("/beeradders", name="beer_adders")
    */
    public function beerAdders(ObjectManager $manager){

        $repository = $this->getDoctrine()->getRepository(beer::class);
        $beers = $repository->findAll();
        
        $repository = $this->getDoctrine()->getRepository(categorie::class);
        $categories = $repository->findAll();

            foreach($beers as $beer){
                $r=rand(0,10);
                $beer->addCategorie($categories[$r]);
            }
        

            $manager->persist($beer);
            $manager->flush();
            return new Response('Saved new beer on country with id');
    }


    /**
    * @Route("/menu", name="menu")
    */
    public function mainMenu(){

        $repository = $this->getDoctrine()->getRepository(Categorie::class);
        $categories = $repository->findByTerm('normale');

        return $this->render('bar/partials/menu.html.twig', ['categories' => $categories]);
    }

    /**
    * @Route("/categorie/{slug}", name="categorie")
    */
    public function categorieBeers($slug){

        $repository = $this->getDoctrine()->getRepository(Categorie::class);
        $categories = $repository->findByTerm('normale');
        

        $categorie = $categories[$slug];
        $beers = $categorie->getBeers();
        

        return $this->render('bar/categorie.html.twig', ['beers' => $beers,
                                                         'title' => 'Bière par catégorie !',
                                                         'categorie' => $categorie
                                                        ]);
    }

    /**
    * @Route("/statistic", name="statistic")
    */
    public function statistic(){

        $repository = $this->getDoctrine()->getRepository(Client::class);
        $clients = $repository->findAll();
        

        return $this->render('bar/statistic.html.twig', ['clients' => $clients,
                                                         'title' => 'Quelques statistiques !',

templates/bar/beer.html.twig
{# Permet d'étendre du template de base #}
{% extends 'base.html.twig' %}

{% block title %}Hello {{ title }}{% endblock %}

{% block stylesheets %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{% endblock %}

{% block beers_list %}
    {% for beer in beers %}
        <li>{{ beer }}</li>
    {% endfor %}
{% endblock %}

{% block footer %}{{ parent() }}{% endblock %}

templates/bar/bestbeer.html.twig
{# Permet d'étendre du template de base #}
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block stylesheets %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{% endblock %}

{% block beers_list %}

            <li>Name : {{ beer.title }}</li>
            <li>Temperature : {{ beer.Degree }} °C</li>
            <li>Price : {{ beer.Price }} €</li>
            <li>Rate : {{ beer.Note }}</li>

{% endblock %}


{% block footer %}{{ parent() }}{% endblock %}

templates/bar/categorie.html.twig
{# Permet d'étendre du template de base #}
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block stylesheets %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{% endblock %}

{% block beers_list %}
    <ul>
        {% for beer in categorie.getBeers %}

            <li>{{ beer.title }}</li>

        {% endfor %}
    </ul>
{% endblock %}


{% block footer %}{{ parent() }}{% endblock %}

templates/bar/country.html.twig
{# Permet d'étendre du template de base #}
{% extends 'base.html.twig' %}

{% block title %}Hello {{ title }}{% endblock %}

{% block stylesheets %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{% endblock %}

{% block name %}{{title}}{% endblock %}

{% block beers_list %}
{% for beers in country.getBeersNew %}
        <li>{{ beers.title }} Beer</li>
{% endfor %}
{% endblock %}

{% block footer %}{{ parent() }}{% endblock %}

templates/bar/index.html.twig
{# Permet d'étendre du template de base #}
{% extends 'base.html.twig' %}

{% block title %}Hello {{ title }}{% endblock %}

{% block stylesheets %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{% endblock %}

{% block body %}
{% endblock %}

{% block beers_list %}
    {% for beer in beers %}
        <li>{{ beer.title }}</li>
        <small>Published at : <b>{{ beer.publishedAt | date('Y-m-d')}}</b></small> 

        {% if beer.countryId %}
            {% for slug, countryId in countries | filter( countryId => countryId.getId == beer.getCountryId.id )  %}                 
                </br><a href="{{ path('show_country', { 'slug' : slug }) }}">
                {{beer.countryId.name }}
                </a>
            {% endfor %}   
        {% endif %}
    {% endfor %}

{% endblock %}

{% block footer %}All copyright reserved 2019{% endblock %}

templates/bar/statistic.html.twig
{# Permet d'étendre du template de base #}
{% extends 'base.html.twig' %}

{% block title %}Hello {{ title }}{% endblock %}

{% block stylesheets %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{% endblock %}

{% block name %}{{title}}{% endblock %}

{% block beers_list %}
<table>
    <tr>
        <td>Name</td>
        <td>Weight</td>
        <td>Beers</td>
    </tr>
    {% for client in clients %}

        <tr>           
            <td>{{ client.name }}</td>



            <td>{{ client.getWeight() }}</td>



            <td>
                <ul>
                    {% for beer in client.getBeer %}
                        <li>{{ beer.title }}</li>
                    {% endfor %}
                </ul>
            </td>        
        </tr>
    {% endfor %}
</table>
{% endblock %}

{% block footer %}{{ parent() }}{% endblock %}

templates/bar/verygood.html.twig
{# Permet d'étendre du template de base #}
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block stylesheets %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{% endblock %}

{% block beers_list %}
    <ul>
        {% for beer in beers %}

            <li>{{ beer.title }}</li>

        {% endfor %}
    </ul>
{% endblock %}


{% block footer %}{{ parent() }}{% endblock %}